Adiciona imagem com PHP 7.4.

diff --git a/php/7.4/Dockerfile b/php/7.4/Dockerfile
--- a/php/7.4/Dockerfile
+++ b/php/7.4/Dockerfile
@@ -1,4 +1,13 @@
-FROM php:7.3-fpm
+FROM php:7.4-fpm
+
+# persistent dependencies
+RUN set -eux; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+# Ghostscript is required for rendering PDF previews
+		ghostscript \
+	; \
+	rm -rf /var/lib/apt/lists/*
 
 # install the PHP extensions we need (https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions)
 RUN set -ex; \
@@ -7,14 +16,15 @@ RUN set -ex; \
 	\
 	apt-get update; \
 	apt-get install -y --no-install-recommends \
+		libfreetype6-dev \
 		libjpeg-dev \
 		libmagickwand-dev \
 		libpng-dev \
 		libzip-dev \
 	; \
 	\
-	docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr; \
-	docker-php-ext-install \
+	docker-php-ext-configure gd --with-freetype --with-jpeg; \
+	docker-php-ext-install -j "$(nproc)" \
 		bcmath \
 		exif \
 		gd \
@@ -47,11 +57,12 @@ RUN { \
 		echo 'opcache.max_accelerated_files=4000'; \
 		echo 'opcache.revalidate_freq=2'; \
 		echo 'opcache.fast_shutdown=1'; \
-		echo 'opcache.enable_cli=1'; \
 	} > /usr/local/etc/php/conf.d/opcache-recommended.ini
-# https://codex.wordpress.org/Editing_wp-config.php#Configure_Error_Logging
+# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
 #RUN { \
-#		echo 'error_reporting = 4339'; \
+## https://www.php.net/manual/en/errorfunc.constants.php
+## https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+#		echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
 #		echo 'display_errors = Off'; \
 #		echo 'display_startup_errors = Off'; \
 #		echo 'log_errors = On'; \
